sudo: false
language: node_js
node_js: '0.12'
script:
- travis-lint .travis.yml
- make eslint
- make stylint
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: GfAzO+FPP7yCXDjf0SsC6a+g18W9GcDug6jdC8xOKRLL2ALbwTx1hB3Trpi7p8HJpYXiy09Fsj51i4K1mtJdTj0xB3PKd5AFoCGdegZ2MxzA1VKta8IzAN+u3pBeBGCxJQgmRdFM2flJ9H4uvAeeYnFMWHF6ycaSSKPJxrL8BD+Fr5hHWxVWSpI5iQ37BEm+znzzbHYIUmcoQLjJYuLJ/imlFBdpYMChBdy3tGOKYzrbkERvpLyB42houZOIR6KzTO0kAtrMjZzvRKbAilEFjpzHiQmyUCCZ9GxAzTTmNRU020SsaZzOtLx53GxA/cOc7nR69Th7OgW6aJ4aPpHfYEtVRgBwE2JOtTVzRkbSfpu3ALOnGK+eAV/5ykGwuhXxLDlSgsb4hqZ7P2V0AVEQpFbvC2lsPB0sd+lzJ3fBxwOPAEaWNqL2oJM8inbWZBubtXLHNhMHTaK4IQRmfdQ+tQeiiN14SBCG3PgdMOJirYEjVwPpwySiZg6fSgp8N89sbZVHZff4H4QILW0Q4xvzYn2OWFtJrZtI7kqieEXlTjWqh/tInE+/tTtJmRyP4iFU5/j7hkF6wLPPHk06hCy3GcJlggiE/2a1vomroNnui8hqthaS53REL7HBMgafAApa5jhXGJzP1Gk6LTzCQIwhyWbV3tUdDyFzqJFNe0Wzdf0=
  app:
    secure: G4muJIi+ZTQc1UTGb7suUWv8uocuMotxC+QnRLXUNPgjym4c+EzcOC6XpWR1mTZSYL8J8n2JX/lfWPFKXQFZMBPoNhzdAraeKhLQ3et/4+m/MKgZMHPLIWyOtn/qYvqy/vxiJZRyOTPXOOSRELJMAFYORil2mw7qVQK5gRHebCHkl4a5rEW/nOwXczHtMcHYdUblYIQuY56qco2nG9zFlrhNo5YmZhqqjXCAlHg1ua9bVNse1gn6i0q3o5HJgEaM4ijE/N697YIuFiCBLGbHN2+Yx89RpvJ2lcIAWqVV2xu+SvzqU/UDLfuFUn2hpppwYgc6P7VTz4Cs2ZOhTV6lrAqQXdZB4CIp9S86lgYuwUvf9KMy006FfyKsMI7/phPXoNY99g91AbwstuwfwezAXzJlv2VbOoJXzfKvfjhoJTGppox4LVNghO5jijB9QCEnkhJ6F0Blkb1JFx33BiJj5drOKUHGyGgL9p8sBQssW7TlkDx2IXLT+YIlSvUh9Sta6XWeJ+cYRTi43MoWcjyVfr2ZPVkFeC/K3QvRGP2FH77yC5602mF8n+qF/gNIIKYmfExz+a3zur1JCiV0Wh56YLxuq2S93YHPJsFlBo2pDVgkDWPepuwU3CPAUlOGXuDMTTTp6c8wcp8YAlbo8UHJNgVr4flucRdCYT1vItvQg90=
